version: '3.7'
networks:
  proxy:

services:

    mongo:
      image: mongo:3
      container_name: mongo
      restart: always
      networks:
          - proxy
    url:
      image: url-shortener:2
      container_name: url
      restart: always
      environment:
        DB_HOST: mongo
        DOMAIN: example.com
      networks:
          - proxy
      ports:
          - "0.0.0.0:3000:3000"


